Home page create dashboard modal
PUM13-2023/pum13-2023 pull request #164
Opened 2023-05-02 11:22 UTC by fallensach

**Changes:**
Modal for adding dashboards are now available. It is a component that can be reused on other pages.
I have added integrated this modal into the home page.
Users can now type in a title and description for their dashboard and add it to the database.

**I have:**

- [x] Set target branch to the correct branch, usually `dev`.
- [x] Rebased source branch from the target branch.
- [x] Ensured code is formatted and linted.
- [x] Cleaned up git history.
- [x] Ensured commit messages describe *what* was changed and *why*.
- [x] Ran tests locally after rebasing and checked output.

2023-05-03 10:53 UTC, haholm requested changes
Overall, nice job! But for architectural, consistency and testing reasons, some changes need to be made.

2023-05-03 10:53 UTC, haholm commented on tests/test_home_page.py
> +        create_dashboard.click()
Could we perhaps test for some response to the button click? For example that the modal is shown?

2023-05-03 10:53 UTC, haholm commented on tests/test_home_page.py
> +        create_dashboard.click()
Is the opening of the modal important in this step if you are just going to unit test the callback? In my opinion, either just test the callback functions with different parameters, or just test the user interface with different inputs using the webdriver.

2023-05-03 10:53 UTC, haholm commented on src/dashboard/pages/index/controller.py
> +def add_dashboard(name: str, desc: str) -> None:
Move this function to the user models file.

2023-05-03 10:53 UTC, haholm commented on src/dashboard/components/add_dashboard_modal.py
> +    )
Move input and multiline_input to seperate components. Also try not to redefine standard python functions, modules or fields such as by naming a function `input()`.

2023-05-03 10:53 UTC, haholm commented on src/dashboard/components/add_dashboard_modal.py
> +                            html.Div(buttons()),
The nesting should be possible to minimize here and maybe in buttons(). These generating functions return a html.Div already.

2023-05-03 10:53 UTC, haholm commented on src/dashboard/components/add_dashboard_modal.py
> +def buttons() -> html.Div:
Consider renaming buttons() and inputs() to generate_buttons() etc. for consistency.

2023-05-05 07:25 UTC, AxelMatstoms commented on src/dashboard/components/text_input.py
> +            html.P(title, className=""),
Using a label element would be preferable here. Also applies to `multiline_input.py`.

2023-05-05 07:25 UTC, AxelMatstoms commented on src/dashboard/pages/index/controller.py
>      return True
This can be simplified. Either `return ctx.triggered_id != "cancel-btn"` or split into two callbacks. I think the second solution would be clearer.

2023-05-05 07:25 UTC, AxelMatstoms commented on src/dashboard/pages/index/controller.py
> +    desc = [input_css, ""]
Don't use lists like this. In my opinion having two variables would more suitable here.

2023-05-05 07:25 UTC, AxelMatstoms commented on src/dashboard/pages/index/controller.py
> +        desc[0] += "h-[17rem]"
Since `h-[17rem]` is always added, perhaps it should be added during initialization?
```python
desc_css = f"{input_css} h-[17rem]"
```

2023-05-05 09:28 UTC, haholm requested changes
Some minor changes.

2023-05-05 09:28 UTC, haholm commented on src/dashboard/pages/index/controller.py
> +    desc_css = f"{deepcopy(input_css)} h-[17rem] "
deepcopy should not be used here as strings are immutable and are already "copied" when assigned to variables or when manipulated.

2023-05-05 09:28 UTC, haholm commented on src/dashboard/components/add_dashboard_modal.py
> +from dashboard.components.text_input import text_input
The new components should be exported in the components/__init__.py module and can then be imported on the same line as modal.

2023-05-22 10:15 UTC, haholm commented on src/dashboard/components/add_dashboard_modal.py
> +from dashboard.components.text_input import text_input
It seems modules from the same directory can not make use of the init.py default exports.

2023-05-22 10:22 UTC, haholm approved these changes

2023-05-22 10:23 UTC, merged