Test creating
PUM13-2023/pum13-2023 pull request #31
Opened 2023-02-27 07:22 UTC by Woshyy

Strukturera testerna och skapade testet för login sidan

2023-02-27 08:47 UTC, AxelMatstoms reviewed
Testerna är ser bra ut!
Går det att flytta pytest config från pytest.ini till pyproject.toml?
Finns det någon anledning att konstanterna ligger i en klass? Känns som att klassen är typ ett namespace bara? Antingen kan de ligga i en ny fil, eller kanske bara precis under import s i test_login.py

2023-02-27 09:33 UTC, YouKnowBlom requested changes
`package.json` i `tests/` verkar ha åkt med av misstag.
Kan vara najs att squasha lite commits också.

2023-02-27 09:33 UTC, YouKnowBlom commented on tests/pytest.ini
> +[pytest]
Körs youtube-testet automatiskt just nu? Känns som att den inte bör göra det då den endast används för att testa att selenium fungerar just nu (och tills att vi kan få det att fungera med GH actions)

2023-02-27 10:39 UTC, Woshyy commented on tests/pytest.ini
> +[pytest]
Fixed

2023-02-28 09:59 UTC, YouKnowBlom approved these changes

2023-02-28 10:00 UTC, merged