DB integration
PUM13-2023/pum13-2023 pull request #55
Opened 2023-03-08 10:14 UTC by AxelMatstoms

**Changes:**
* Add database models for user, dashboard and diagram.
* User model supports login of users

**I have:**

- [x] Set target branch to the correct branch, usually `dev`.
- [x] Ensured code is formatted, linted.
- [x] Cleaned up git history.
- [x] Ensured commit messages describe *what* was changed, and *why*.
- [x] Ran tests locally, checked output.

2023-03-08 11:33 UTC, fallensach commented on src/dashboard/models/user.py
> +    A diagram stores all the information needed to reconstruct a Dast
Typo?

2023-03-08 13:57 UTC, YouKnowBlom approved these changes

2023-04-19 09:33 UTC, haholm approved these changes
Looks great! Good job.

2023-04-19 11:04 UTC, TobiasElf requested changes
Mostly looks good. Some comments about comments mostly

2023-04-19 11:19 UTC, AxelMatstoms commented on src/dashboard/models/data.py
> +# TODO: to polars df
#139

2023-04-19 11:39 UTC, AxelMatstoms commented on src/dashboard/models/user.py
> +    Logins as a user, creating the user if it does not exists.
My understanding is that this is expected behavior. A login system is not a requirement, so we don't want to spend time writing code for storing passwords etc.

2023-04-19 11:45 UTC, AxelMatstoms commented on src/dashboard/models/data.py
> +        self.markers = [Marker(**marker) for marker in self.markers]  # type: ignore
Possible, but requires another field to store the list of dicts. Would be kind of ugly imo.

Resolved by adding an inline comment explaining this.

2023-04-19 11:45 UTC, AxelMatstoms commented on src/dashboard/models/db.py
> +        raise EnvironmentError(f"Can't find environment variable {DB_URL_ENV_NAME}")
:+1:

2023-04-19 11:45 UTC, AxelMatstoms commented on src/dashboard/models/user.py
> +        A User object returning the newly created user.
Yes, this was a typo.

2023-04-19 11:47 UTC, TobiasElf approved these changes
LGTM!

2023-04-19 11:47 UTC, merged